server:
  port: 80

spring:
  application:
    name: cloud-order-service
eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
#    lease-expiration-duration-in-seconds: 2 #距离最后一次发送心跳给服务器过去30秒后 服务器准备移除这个服务;默认90秒
#    lease-renewal-interval-in-seconds: 1 #指定客户端给eureka服务器发送心跳的频率 默认30秒发一次

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
