server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #指定在注册中心注册显示的名称

  datasource: #数据库连接参数及druid相关参数
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123

    # druid数据源属性
    initial-size: 8
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runsMillis: 60000
    min-evictable-idle-timeMillis: 300000
    validation-query: select 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-open-prepared-statements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true
    instance-id: payment8001
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka #eureka集群地址
