server:
  port: 83

spring:
  application:
    name: cloud-nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
